### ISSUE TITLE
Add more comments

### ISSUE THREAD

**Issue by BlackBrad** [BlackBrad/Asteroids#12]
I need to add more comments to make this program easier to read.

**Comment by crookm** [comment]
Okay, good job.

**Comment by BlackBrad** [comment]
But I'm afraid I haven't done it yet. 
![32zkils](https://cloud.githubusercontent.com/assets/12821798/8919654/569c9a82-3515-11e5-98c6-6b7c66407b5b.jpg)

**Comment by crookm** [comment]
It's okay! Just remember to have fun and be yourself!

**Comment by BlackBrad** [comment]
I will!
![cjwa0fruwaa8ouf](https://cloud.githubusercontent.com/assets/12821798/8919686/8d67a9a8-3515-11e5-8375-c359a002e3e1.jpg)

**Comment by crookm** [comment]
too much.

**Comment by BlackBrad** [comment]
You jelly?

**Comment by crookm** [comment]
![image](https://cloud.githubusercontent.com/assets/12828808/8919739/182b1890-3516-11e5-9bf8-a837dd3cd516.png)

**Comment by BlackBrad** [comment]
No. You defintaly are.
![skiffy - mysticsolace](https://cloud.githubusercontent.com/assets/12821798/8919705/c6f60c82-3515-11e5-95c3-05d783b36dac.png)

**Comment by crookm** [comment]
Did you have the authors permission to upload that picture?

**Comment by BlackBrad** [comment]
Actually I do. It was a free to use line-art that someone I know coloured for me.
