### ISSUE TITLE
Asteroid Spawn Rate

### ISSUE THREAD

**Issue by BlackBrad** [BlackBrad/Asteroids#13]
Is suppsod to decrease every second. Suprise suprise it does not.

**Comment by crookm** [comment]
ok.

**Comment by BlackBrad** [comment]
Oops I spelt 'supposed' wrong!
![175267-spongebob-square-pants-mr-krabs-funny-face](https://cloud.githubusercontent.com/assets/12821798/9296179/b90d6d16-44da-11e5-9a89-ff53c5ebb4fa.jpg)

**Comment by crookm** [comment]
Please never again

**Comment by BlackBrad** [comment]
More did I hear you say? 
![images](https://cloud.githubusercontent.com/assets/12821798/9296190/ea89fc1a-44da-11e5-9e0b-ebc8f5092542.jpg)
