### ISSUE TITLE
Asteroid Collision

### ISSUE THREAD

**Issue by BlackBrad** [BlackBrad/Asteroids#4]
If asteroids collide they move off in opposite directions at random speeds.

**Comment by BlackBrad** [comment]
Actually don't need to do this in the program so I'm closing this issue.

**Comment by crookm** [comment]
What a shame, that would have been cool.

**Comment by BlackBrad** [comment]
I do suppose that could be my extra feature thing. Only problem is when there is a large amount of asteroids and they all get stuck inside of each other.
