### ISSUE TITLE
If ship moves off screen it reappears on the oppoiste side

### ISSUE THREAD

**Issue by BlackBrad** [BlackBrad/Asteroids#8]
If the ship moves off the playing screen then it reappears on the other side of the playing screen.

**Comment by crookm** [comment]
Re-appears on the other side? Just up and down or left and right? Because if you implement this left and right, you could move right into an asteroid.

**Comment by BlackBrad** [comment]
How very true crookm. In that case I'll make it so that the ship cannot move less than 0 of the canvas width or more than the canvas width.

**Comment by crookm** [comment]
> How do you think will will affect blind people?  
I don't believe blind people could play this game...
